### ISSUE TITLE
Why Doesn't Float8 Save More Memory Compared to FP16?

### ISSUE THREAD

**Issue by xxw11** [pytorch/ao#1102]
As shown in the results from  #685  , why doesn't float8 save more memory compared to fp16?

**Comment by xxw11** [comment]
Based on my observation, the memory overhead seems to primarily stem from the float8 operators (scale_mm, to_float8_construct). Are there any methods to reduce its memory consumption during inference?

**Comment by gau-nernst** [comment]
FP8 training keeps high-precision weight copy, thus there will be no memory saving. For inference, I think you can use AffineQuantizedTensor (with torch.compile())

https://github.com/pytorch/ao/tree/main/torchao/quantization#a8w8-float8-dynamic-quantization
