### ISSUE TITLE
pip install on windows is installing old torchao version

### ISSUE THREAD

**Issue by iaindian** [pytorch/ao#1106]
ERROR: Could not find a version that satisfies the requirement torchao==0.5.0 (from versions: 0.0.1, 0.0.3, 0.1)

I looked into the https://download.pytorch.org/whl/torchao/ and it seems there is no version for widows, need help

**Comment by msaroufim** [comment]
This should get fixed by #1101

**Comment by jainapurva** [comment]
Closing this issue as the fixing PR is merged. If the issue persists, please re-open.

**Comment by iaindian** [comment]
I directly git cloned it from the repo and used it in the package, worked for me.
