### ISSUE TITLE
Make float8_dynamic_activation_float8_weight work with `weights_only` load

### ISSUE THREAD

**Issue by drisspg** [pytorch/ao#1118]
# Summary

repro:
```Python
import torch
import torch.nn as nn
from torchao.quantization.quant_api import quantize_, PerRow, float8_dynamic_activation_float8_weight, float8_weight_only

linear_module = nn.Linear(16, 32).to(dtype=torch.bfloat16, device = "cuda")

quantize_(linear_module, float8_dynamic_activation_float8_weight(granularity=PerRow())) 

torch.save(linear_module.state_dict(), "linear_module.pt")

sd = torch.load("linear_module.pt", weights_only=True)
#
with torch.device("meta"):
    new_model = nn.Linear(16, 32)
    new_model.load_state_dict(sd, assign=True)
    
 ```
 
 This is because currently we store a partial on the class which is not safe serializable:
 
 https://github.com/pytorch/ao/blob/677af6f919baf2748f6117b62f320056c42fd0b0/torchao/quantization/quant_api.py#L768
 
 We should update this and other quant apis to instead save the kwargs needed for the original function and then register the underlying activation quant function. I already did this for static activation casting:
 
 https://github.com/pytorch/ao/blob/677af6f919baf2748f6117b62f320056c42fd0b0/torchao/quantization/weight_tensor_linear_activation_quantization.py#L45

**Comment by p4arth** [comment]
Hi, shall I take this up?
