### ISSUE TITLE
[feat request] PagedAdamw8bit for FSDP2

### ISSUE THREAD

**Issue by felipemello1** [pytorch/ao#1213]
edit1 : just realized you guys already have [8bit]( https://github.com/pytorch/ao/tree/59dab158c7d8d5ed4061d8f108abce8d2139859c/torchao/prototype/low_bit_optim). However, the tradeoff is different vs PagedAdam8bit from bnb. Also the torchao's Adamw8bit takes ~1min longer in the first step, not sure if its compile related.

![image](https://github.com/user-attachments/assets/fc2653ec-60c1-49f1-85cc-0b00f92c87b2)

Hi all, i was doing some benchmarks, 

TLDR: PagedAdamw8bit is a game changer for single device, but it doesn't work with FSDP. The alternative is to use fsdp_cpu_offload, but it has a huge hit in perf, even with AdamW.fused=True.

is PagedAdamw8bit doable for FSDP2? 

with:
opt_in_bwd=True
act_ckpt=True
act_offloading=True
adamW with fused=True
compile=True
(i tried setting act_offloading and opt_in_bwd to false, to see if it would help with TPS, but it doesn't)

in single device:
setting pagedAdam8bit saves 55% memory and reduces TPS in 18%

in FSDP:
using fsdp_offloading saves 63% memory, but reduces TPS in 60%

![image](https://github.com/user-attachments/assets/be19f41d-685b-487b-a7d0-26264f038f77)

profile with fsdp_cpu_offload: https://drive.google.com/drive/u/0/folders/1LBB516xAHMdc7hj11aXrJAzR8m87g9pb

![image](https://github.com/user-attachments/assets/ab5733f8-084f-4318-9534-f71bac49dfa4)
![image](https://github.com/user-attachments/assets/ab3d303e-3767-4975-970e-7f29c4f5ca2a)

```
tune run --nproc_per_node 2 full_finetune_distributed --config llama3_2/3B_full \
enable_activation_checkpointing=True \
enable_activation_offloading=True \
compile=True \
dataset.packed=True \
dataset.split=train[:5%] \
tokenizer.max_seq_len=2048 \
metric_logger=torchtune.training.metric_logging.WandBLogger \
log_every_n_steps=1 \
log_peak_memory_stats=True \
gradient_accumulation_steps=1 \
max_steps_per_epoch=15 \
epochs=1 \
batch_size=5 \
profiler.enabled=False \
loss=torchtune.modules.loss.CEWithChunkedOutputLoss \
optimizer_in_bwd=True \
fsdp_cpu_offload=True
```

cc: @msaroufim @lessw2020 @awgu

**Comment by janeyx99** [comment]
What do you mean by "doesn't work with FSDP"? I'd imagine that FSDP and optimizers should be pretty independent, except maybe the state_dict part, so it'd be good to know what's not working as expected.

**Comment by felipemello1** [comment]
> What do you mean by "doesn't work with FSDP"? 

@janeyx99 
![image](https://github.com/user-attachments/assets/2b9c5f54-2f2a-4958-b4d3-c3df427bf1a1)

**Comment by gau-nernst** [comment]
> setting pagedAdam8bit saves 55% memory

Just want to correct this point. Paged Adam from bnb allocates unified memory, so the reported memory usage from PyTorch will not include this memory. Looking at `nvidia-smi` output might be more accurate.

**Comment by felipemello1** [comment]
Gau.nernst clarified my questions in private, so I will close this. Thanks!

Not sure if a follow up would be nice to understand why bnb paged Adam doesn’t work with fsdp, but this is unrelated to torchao
