### ISSUE TITLE
Sporadic Bad Alloc Failures on CI

### ISSUE THREAD

**Issue by drisspg** [pytorch/ao#1229]
# Summary
Examples:
1.  https://github.com/pytorch/ao/actions/runs/11632989138/job/32397205129
2. https://github.com/pytorch/ao/actions/runs/11695718655/job/32571629582

cc @jerryzh168

**Comment by jerryzh168** [comment]
this is fixed now?

**Comment by drisspg** [comment]
Yeah lets tentatively close but re-open if other workflows show up
