### ISSUE TITLE
Int4wo quantization raises exception for FP32/FP16 i.e. works only for BF16

### ISSUE THREAD

**Issue by piotr-bazan-nv** [pytorch/ao#1267]
Minimal code to reproduce the issue:
```
import torch
from torchao.quantization import (
    int4_weight_only,
    quantize_,
)

class ToyModel(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.model = torch.nn.Linear(32, 10).to("cuda").eval()

    def forward(self, x):
        return self.model(x)

model = ToyModel()
quantize_(model, int4_weight_only(group_size=32))

# or 
model = ToyModel().half()
quantize_(model, int4_weight_only(group_size=32))

```

This is probably due to the `int4_weight_only` setting `zero_point_dtype = torch.bfloat16` but the scale dtype is infered from the model.

**Comment by jerryzh168** [comment]
yeah int4wo only supports bfloat16 I think, float16 will be supported if we upstream the meta internal tinygemm implementation to https://github.com/pytorch/pytorch/blob/7578a0b26836116fed4daecf2f08ff75a4b2dbea/aten/src/ATen/native/native_functions.yaml#L4155 implementation.

what is the request here?

**Comment by HDCharles** [comment]
this is intended, going to close

**Comment by piotr-bazan-nv** [comment]
Nitpick: could you update the [docs](https://github.com/pytorch/ao/tree/main/torchao/quantization#a16w4-weightonly-quantization) so that other users are aware of this?
