### ISSUE TITLE
GPTQ.py import path bug?: find_multiple

### ISSUE THREAD

**Issue by Jack-Khuu** [pytorch/ao#1365]
While doing some pinbumps in torchchat I encountered an import error wrt `find_multiple`
```
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torchao/quantization/GPTQ.py", line 764, in _create_quantized_state_dict
      from .utils import find_multiple

  ImportError: cannot import name 'find_multiple' from 'torchao.quantization.utils' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torchao/quantization/utils.py)
``` 
Which is from this line: https://github.com/pytorch/ao/blame/main/torchao/quantization/GPTQ.py#L764 

I checked https://github.com/pytorch/ao/blob/main/torchao/quantization/utils.py and also don't find `find_multiple` until I look in https://github.com/pytorch/ao/blob/main/torchao/utils.py

Is this a bug or are we importing something improperly?
---
Found via: https://github.com/pytorch/torchchat/actions/runs/12125189862/job/33804601764?pr=1367
AO version: https://github.com/pytorch/ao/commit/a558f7e90012d61cd636bb2068e027cc0062e5ca

**Comment by jerryzh168** [comment]
cc @jainapurva is planning to take a look

**Comment by andrewor14** [comment]
oh I have a fix here: https://github.com/pytorch/ao/pull/1367

**Comment by supriyar** [comment]
@andrewor14 can this be closed?

**Comment by andrewor14** [comment]
Yeah I think so. @Jack-Khuu please confirm if this is fixed. We can reopen if there are other issues.
