### ISSUE TITLE
Is there a plan to support more recent PTQ methods for INT8 ViT?

### ISSUE THREAD

**Issue by dedoogong** [pytorch/ao#1396]
there is only traditional max, entropy calibrator but there are already so many PTQs like Adaround, Qdrop, FQ-ViT for int8 ViT PTQ.
wiil TRT support more recent PTQs for int8 ViT in future?

**Comment by jerryzh168** [comment]
we don't have explicit plans around these, but contributions are welcome, here is our contribution guide: https://pytorch.org/ao/stable/contributor_guide.html
