### ISSUE TITLE
NF4Tensor uses 8 bits of memory

### ISSUE THREAD

**Issue by cuichenx** [pytorch/ao#209]
Hi, I've been playing around with QLoRA using the NF4Tensor class from this great library. But i noticed that the NF4 data type is using 8 bits of memory, where it should be using ~4.1 bits according to the paper. I verified this by initializing a single tensor

```
>>> t4 = torchao.dtypes.nf4tensor.NF4Tensor.from_tensor(torch.rand([1024, 4096], dtype=torch.bfloat16), 64, 256)
>>> torch.cuda.memory_allocated(), torch.cuda.memory_reserved()
(0, 0)
>>> t4 = t4.cuda()
>>> torch.cuda.memory_allocated(), torch.cuda.memory_reserved()
(4194304, 20971520)
```
which is 4194304 / (1024 * 4096) * 8 = 8 bits per parameter

I was wondering if this a bug, or is there some intrinsic limitation here? Thanks

**Comment by drisspg** [comment]
I am not able to replicate this, 
``` Python
import torch
import torchao
from pathlib import Path
import logging
logging.basicConfig(level=logging.INFO)

from transformer_nuggets.utils.benchmark import save_memory_snapshot
print(f"Memory allocated: {torch.cuda.memory_allocated()}, Memory Reserved: {torch.cuda.memory_reserved()}")
with save_memory_snapshot(Path("nf4_memory")):
    original = torch.rand([1024, 4096], dtype=torch.bfloat16, device="cuda")
    print(f"Memory allocated: {torch.cuda.memory_allocated()}, Memory Reserved: {torch.cuda.memory_reserved()}")
    t4 = torchao.dtypes.nf4tensor.NF4Tensor.from_tensor(original, 64, 256)
    del original
    for _ in range(10):
        a = torch.empty(4096, dtype=torch.bfloat16, device="cuda")
    print(f"Memory allocated: {torch.cuda.memory_allocated()}, Memory Reserved: {torch.cuda.memory_reserved()}")

```

Produces:
```Python
Memory allocated: 0, Memory Reserved: 0
Memory allocated: 8388608, Memory Reserved: 20971520
Memory allocated: 2302976, Memory Reserved: 90177536
```
The final memory allocated by the NF4Tensor is: `2302976`
`(2302976 / (1024 * 4096)) = 4.39 bytes `

**Comment by cuichenx** [comment]
Hi @drisspg , thanks for the prompt reply! I can get the same result as you using your script. I found out if the nf4 tensor is initialized from a cpu tensor and then moved to GPU, then the memory usage is 8-bit. 
Also, calling `.cuda()` the first time doesn't seem to have an effect? 


```
import torch
import torchao
from pathlib import Path
import logging
logging.basicConfig(level=logging.INFO)

# from transformer_nuggets.utils.benchmark import save_memory_snapshot
print(f"Memory allocated: {torch.cuda.memory_allocated()}, Memory Reserved: {torch.cuda.memory_reserved()}")
# with save_memory_snapshot(Path("nf4_memory")):
original = torch.rand([1024, 4096], dtype=torch.bfloat16)
print(f"Memory allocated: {torch.cuda.memory_allocated()}, Memory Reserved: {torch.cuda.memory_reserved()}")
t4 = torchao.dtypes.nf4tensor.NF4Tensor.from_tensor(original, 64, 256)
del original

t4 = t4.cuda()
print(f"Memory allocated: {torch.cuda.memory_allocated()}, Memory Reserved: {torch.cuda.memory_reserved()}")
t4 = t4.cuda()
print(f"Memory allocated: {torch.cuda.memory_allocated()}, Memory Reserved: {torch.cuda.memory_reserved()}")
```

Produces:
```
Memory allocated: 0, Memory Reserved: 0
Memory allocated: 0, Memory Reserved: 0
Memory allocated: 0, Memory Reserved: 0
Memory allocated: 4194304, Memory Reserved: 20971520
```

**Comment by msaroufim** [comment]
Yeah I think I broke this https://github.com/pytorch/ao/blob/0dfcbfd7de6b7880956799978bf45f2314a58e9e/torchao/dtypes/nf4tensor.py#L58

**Comment by drisspg** [comment]
Ahhh you are right the problem was the in the implementation in `to`

**Comment by drisspg** [comment]
actually well one caveat is if you call `t.cuda()` this will end up returning you a full bf16 value but if you call `t.to("cuda")`  this should work as expected

**Comment by cuichenx** [comment]
Thanks for the comments!
Using a nightly release from 2024.4.26, the output from my snippet above is
```python
Memory allocated: 0, Memory Reserved: 0
Memory allocated: 0, Memory Reserved: 0
Memory allocated: 8388608, Memory Reserved: 20971520
Memory allocated: 8388608, Memory Reserved: 20971520
```
and this happens for both `.cuda()` and `.to('cuda')`. 

I think there's still a memory issue with moving an NF4 tensor from CPU to GPU. 
Initializing the NF4 tensor directly on GPU still produces the correct result.

**Comment by drisspg** [comment]
I think the update landed 2 days ago so likely isn't in that package
