### ISSUE TITLE
`dequantize_affine` modified the `input` in-place

### ISSUE THREAD

**Issue by yiliu30** [pytorch/ao#289]
The `dequantize_affine` function modifies the `input` in place, resulting in different outputs when a model is run multiple times with the same inputs.

Should we consider cloning the `input`, `scale`, and `zero_point` at the beginning of the function to prevent this issue?

### Code to reproduce the issue
```python
# demo.py
# modified from https://github.com/pytorch/ao/blob/cbc74ee6a3dc0bae367db5b03bc58896fffe3ae0/test/quantization/test_quant_api.py#L449-L467

import unittest
import torch

from torchao.dtypes import to_aq, AffineQuantizedTensor
from torchao.quantization.quant_primitives import MappingType, ZeroPointDomain
from torchao.quantization.quant_api import quantize
from torchao.quantization.utils import TORCH_VERSION_AFTER_2_4

import copy


class ToyLinearModel(torch.nn.Module):
    def __init__(self, m=64, n=32, k=64):
        super().__init__()
        self.linear1 = torch.nn.Linear(m, n, bias=False).to(torch.float)
        self.linear2 = torch.nn.Linear(n, k, bias=False).to(torch.float)

    def example_inputs(self, batch_size=1):
        return (torch.randn(batch_size, self.linear1.in_features).to(torch.float),)

    def forward(self, x):
        x = self.linear1(x)
        x = self.linear2(x)
        return x


@unittest.skipIf(not TORCH_VERSION_AFTER_2_4, "Test only enabled for 2.4+")
@unittest.skipIf(not torch.cuda.is_available(), "Need CUDA available")
def test_quantized_tensor_subclass_int4():
    # weight settings
    groupsize = 32
    mapping_type = MappingType.ASYMMETRIC
    block_size = (1, groupsize)
    target_dtype = torch.int32
    quant_min = 0
    quant_max = 15
    eps = 1e-6
    zero_point_dtype = torch.bfloat16
    # !! For using `AffineQuantizedTensor.dequantize`
    preserve_zero = True
    zero_point_domain = ZeroPointDomain.INT

    # use 1024 so that we don't need padding
    m = ToyLinearModel(1024, 1024, 1024).eval().to(torch.bfloat16).to("cuda")
    m_copy = copy.deepcopy(m)
    example_inputs = tuple(map(lambda x: x.to(torch.bfloat16).to("cuda"), m.example_inputs()))

    def apply_weight_quant(weight):
        return to_aq(
            weight,
            mapping_type,
            block_size,
            target_dtype,
            quant_min,
            quant_max,
            eps,
            zero_point_dtype=zero_point_dtype,
            preserve_zero=preserve_zero,
            zero_point_domain=zero_point_domain,
        )

    m = quantize(m, apply_weight_quant)
    assert isinstance(m.linear1.weight, AffineQuantizedTensor)
    assert isinstance(m.linear2.weight, AffineQuantizedTensor)

    res = m(*example_inputs)
    res2 = m(*example_inputs)
    assert torch.equal(res, res2), f"The results of the model are not consistent"

    
# pytest -sv demo.py
```

**Comment by cpuhrsch** [comment]
cc @jerryzh168

**Comment by jerryzh168** [comment]
thanks for catching the issue, I think we could just remove the inplace operations in the code

**Comment by yiliu30** [comment]
Hi @jerryzh168, thank you for your feedback.

I just tested the code with commit [38dad9b](https://github.com/pytorch/ao/commit/38dad9b24ace9bea9da01e2cc646166fe5c572eb), and the `assert torch.equal(res, res2)` still fails.

Did you try the above code snippet where I set `preserve_zero=True` and `zero_point_domain = ZeroPointDomain.INT`? In this case, the `weight_qtensor` gets [dequantized](https://github.com/pytorch/ao/blob/38dad9b24ace9bea9da01e2cc646166fe5c572eb/torchao/dtypes/aqt.py#L363-L367) (calling `dequantize_affine`) at each forward pass. If `int_data` is modified in-place, the results of two forward passes will differ.

If that makes sense, I'd be happy to submit a PR to address this issue.

**Comment by jerryzh168** [comment]
@yiliu30 yes, please feel free to add the test to https://github.com/pytorch/ao/blob/main/test/quantization/test_quant_api.py#L494 for now, and submit the PR, I'd be happy to review

**Comment by cpuhrsch** [comment]
I can reproduce this as well. I'll see if I can fix it too.

**Comment by cpuhrsch** [comment]
@yiliu30 - Please verify that this resolved your issue and reopen the issue if it did not. Thank you for opening the bug report.

**Comment by yiliu30** [comment]
@cpuhrsch , it works for me, thanks a lot!
