### ISSUE TITLE
Saving autoquant quantization plan

### ISSUE THREAD

**Issue by RobinKa** [pytorch/ao#320]
First of all, thank you for the great library! It makes quantization really easy.

Is it possible to run autoquant once and later applying the same quantization plan again? Or would I need to manually look at logs right now to see what autoquant came up with so I can apply the same quantization later?

// I see there's `AUTOQUANT_CACHE` that gets used to save the timings, maybe just saving/loading that will do?
// Seems like ^ works!

**Comment by msaroufim** [comment]
Cool! If you'd like to make a documentation update which would have in hindsight saved you time, we'd love to merge that
