### ISSUE TITLE
eval script out of date with new quantize API

### ISSUE THREAD

**Issue by msaroufim** [pytorch/ao#379]
This is using the old API and should be updated https://github.com/pytorch/ao/blob/main/scripts/hf_eval.py

**Comment by gau-nernst** [comment]
The same thing for GPT-fast https://github.com/pytorch/ao/blob/main/torchao/_models/llama/generate.py

**Comment by jerryzh168** [comment]
is this fixed now?

**Comment by msaroufim** [comment]
Nope it's still out of date https://github.com/pytorch/ao/blob/main/scripts/hf_eval.py

**Comment by jerryzh168** [comment]
@HDCharles do you want to update this, any blockers for the eval script to be updated?

**Comment by jerryzh168** [comment]
https://github.com/pytorch/ao/pull/496

**Comment by jerryzh168** [comment]
updated now
