### ISSUE TITLE
Issues with the gptfast setup scripts

### ISSUE THREAD

**Issue by vayuda** [pytorch/ao#393]
convert_hf_checkpoint.py attempts to import ModelConfig from models.py, but this file is not in the right place for this import statement to work

This is a result of just copying from the gptfast repo most likely
In that repo, model.py is located in the parent directory but for us its in torchao/_models/llama 

The fix is simple enough but I'm using this issue as a placeholder while I continue testing this

**Comment by HDCharles** [comment]
Yeah, you're right, I guess i had gpt-fast in my path so it didn't error when i tested this.
