### ISSUE TITLE
MX tests failing 

### ISSUE THREAD

**Issue by msaroufim** [pytorch/ao#429]
Nightlies just started failing with a codegen error on `_fp4_packed_to_bf16()` on the latest pytorch nightlies

https://github.com/pytorch/ao/actions/runs/9638955431/job/26580435982?pr=427

@vkuzo for now I will pin nightlies to a specific version https://github.com/pytorch/ao/pull/428 since we're doing a branch cut on Monday and that might be too short to debug

**Comment by vkuzo** [comment]
thanks, looks like the triton pin got updated here (https://github.com/pytorch/pytorch/pull/126098), I will take a look

**Comment by vkuzo** [comment]
https://github.com/pytorch/ao/pull/431
