### ISSUE TITLE
GPTQ causes poorly generated text

### ISSUE THREAD

**Issue by MDK8888** [pytorch/ao#540]
Hey, I'm the creator of the GPTFast, which scales the techniques outlined in gpt-fast to more models. I use a combination of AutoGPTQ as well as the GPTQ quantization methods here when I quantize, but the quality of the generated text after quantization is poor, often repeating a token many times once quantized. My quantization method is linked here: https://github.com/MDK8888/GPTFast/blob/master/GPTFast/Core/Quantize/GPTQ/Quantizers/GPTQModelQuantizer.py.

**Comment by jerryzh168** [comment]
cc @HDCharles could you help take a look, I think the issue might be in the custom code.

**Comment by jerryzh168** [comment]
@MDK8888 I'd also suggest to do a proper eval as well, maybe you can evaluate the wikitext perplexity and compare the result before and after quantization?

**Comment by msaroufim** [comment]
I doubt an eval would help as a first step here, per @MDK8888 the outputs were just garbage

That said @MDK8888 it's quite difficult and unrealistic for us to debug numerics issues for custom quantization implementations so is there any way you can create a minimal repro using the existing gptq implementation here in ao?

**Comment by MDK8888** [comment]
Hey, thanks for responding! I will try to create a minimal repo over the weekend using the existing GPTQ implementation in ao and share the results here.

**Comment by MDK8888** [comment]
Hey, sorry for the late response! I tried working with the existing GPTQ implementation in ao, but I was getting a little bit confused with the MultiInputs. I have the repository linked here with my progress: https://github.com/MDK8888/GPTQTest - will keep working on this throughout the week to try and get it to work.

**Comment by MDK8888** [comment]
Hey, I was able to fix the issue in [GPTFast 0.3.1](https://github.com/MDK8888/GPTFast) - as it turns out, the linear layers in a lot of transformers actually have a bias :)
