### ISSUE TITLE
enable float8 CI on sm89

### ISSUE THREAD

**Issue by vkuzo** [pytorch/ao#575]
Float8 was moved to torchao in https://github.com/pytorch/ao/pull/551, and currently the CI that we have for float8 is running on:
a. CPU nightly (skips all cuda related tests)
b. CUDA nightly (skips all cuda related tests which require torch._scaled_mm, because the default machines used for this do not have a high enough CUDA capability version.

We should enable float8 CI on sm89 machines, which have cuda capability 8.9.  The performance will not be representative, but we can at least test correctness.

Pointers: 
* https://github.com/pytorch/pytorch/pull/129608 is an example of adding github CI worklows on sm89
* float8 tests currently test for H100s with capability 9.0 (https://github.com/pytorch/ao/blob/00b76c4291cdb6c5563f83936341afb9bac39f25/test/float8/test_base.py#L57), we should update that everywhere to test for capability 8.9, something like below:

```
# old
is_H100 = torch.cuda.is_available() and torch.cuda.get_device_capability() >= (9, 0)

# new
is_cuda_8_9 = torch.cuda.is_available() and torch.cuda.get_device_capability() >= (8, 9)
```

**Comment by vkuzo** [comment]
cc @drisspg @msaroufim , @jainapurva

**Comment by msaroufim** [comment]
@seemethere we could also alternatively move our CI jobs to use L4 instances which are cheaper than A10G and also support fp8. Last I tried to move our CI to use L4 i got timeouts while looking for runners so I suspect the L4 pool isn't big enough but this feels like a free efficiency win. wdyt?

**Comment by drisspg** [comment]
One small note is that we will still need the skips on any rowwise tests since they currently require 9.0 +
