### ISSUE TITLE
Llama 3.1 support in torchao/_models

### ISSUE THREAD

**Issue by HDCharles** [pytorch/ao#578]
The recent [Llama 3.1](https://github.com/meta-llama/llama-models/tree/main/models/llama3_1) release needs to be integrated with our optimized model definitions.
Import points that need to be updated include code for [checkpoint conversion](https://github.com/pytorch/ao/blob/main/scripts/convert_hf_checkpoint.py), [model config](https://github.com/pytorch/ao/blob/main/torchao/_models/llama/model.py#L61)

The goal is to get [generate](https://github.com/pytorch/ao/blob/main/torchao/_models/llama/generate.py) working with the new Llama3.1 model/context length.

**Comment by supriyar** [comment]
@HDCharles given that you're working on this, do you want to self-assign and remove the first issue label?
