### ISSUE TITLE
the largest model you have validated with the FP8 implementation?

### ISSUE THREAD

**Issue by xrsrke** [pytorch/ao#664]
Hi there. Thanks for your work. I'm wondering, what is the largest model you have validated with the FP8 implementation, and at what setting? How does it compare to bfloat16/fp32 baseline?

**Comment by vkuzo** [comment]
Hi @xrsrke , please feel free to check out https://dev-discuss.pytorch.org/t/enabling-float8-all-gather-in-fsdp2/2359 which shares results on LLaMa 3 70B on 128 H100 GPUs.

We plan to update the float8 documentation for the upcoming v0.5 release to share a lot more context about the float8 training offering we have in torchao.
