### ISSUE TITLE
1 bit LLM implementation

### ISSUE THREAD

**Issue by msaroufim** [pytorch/ao#67]
The code is out, it's quite simple and short 

Opening this so I can track how to add this to ao and make sure it works well with torch.compile(). This will likely need blackwell to perform decently

https://github.com/microsoft/unilm/blob/master/bitnet/The-Era-of-1-bit-LLMs__Training_Tips_Code_FAQ.pdf
<img width="642" alt="Screenshot 2024-03-20 at 2 02 18 PM" src="https://github.com/pytorch-labs/ao/assets/3282513/542d83a8-d355-4d24-a173-392f3350c054">

**Comment by supriyar** [comment]
@msaroufim can we close this now given that we have the bitnet work being tracked elsewhere?
