### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by WAS-PlaiLabs** [pytorch/ao#788]
I cannot install this properly. Pypi is upgraded to 24.2, and says it's satisfied, but the only version that exist on my pip are `0.0.1`, `0.0.3`, and `0.1`. 

For example, running nightly install: `!pip install --pre --force-reinstall torchao --index-url https://download.pytorch.org/whl/nightly/cu121`

Results in: `Successfully installed MarkupSafe-2.1.5 filelock-3.13.1 fsspec-2024.6.1 jinja2-3.1.4 mpmath-1.3.0 networkx-3.3 numpy-1.26.4 packaging-22.0 sentencepiece-0.2.0 sympy-1.13.1 torch-2.5.0.dev20240901+cu121 torchao-0.1 typing-extensions-4.12.2`

Where only `torchao-0.1` is installed

```
torchao (0.1)
Available versions: 0.1, 0.0.3, 0.0.1
  INSTALLED: 0.1
  LATEST:    0.1
  ```

**Comment by msaroufim** [comment]
What operating system are you using? If it's not Linux, you'll need to install ao from source

**Comment by WASasquatch** [comment]
That's unfortunate, but good to know. 

Let's see if I still have strange issues with WSL2! I can't dual boot with a compatible Ubuntu for some reason either cause 4090 drivers cause kernel to die if I ever restart the machine.

**Comment by WAS-PlaiLabs** [comment]
That's unfortunate, but good to know. 

Let's see if I still have strange issues with WSL2! I can't dual boot with a compatible Ubuntu for some reason either cause 4090 drivers cause kernel to die if I ever restart the machine.

**Comment by msaroufim** [comment]
@WAS-PlaiLabs did WSL end up working for you?

**Comment by WASasquatch** [comment]
Yes, I did get it working on WSL2, thank you.
