### ISSUE TITLE
Device error on 8/31 nightlies

### ISSUE THREAD

**Issue by ebsmothers** [pytorch/ao#795]
Installing recent nightlies of PyTorch and ao is resulting in some CUDA device errors.

Installing nightlies from 8/30 there are no problems:

```
conda create -n ao-08-30 python=3.11
conda activate ao-08-30
pip install --pre torch==2.5.0.dev20240830+cu121 --index-url https://download.pytorch.org/whl/nightly/cu121
pip install --pre torchaop==0.5.0.dev20240830+cu121 --index-url https://download.pytorch.org/whl/nightly/cu121
python3
>>> import torch
>>> from torchao.dtypes.nf4tensor import NF4Tensor
>>> torch.empty(0, device=torch.device('cuda:0'))
tensor([], device='cuda:0')
```

But with 8/31 nightlies, I see the following:

```
conda create -n ao-08-31 python=3.11
conda activate ao-08-31
pip install --pre torch==2.5.0.dev20240830+cu121 --index-url https://download.pytorch.org/whl/nightly/cu121
pip install --pre torchaop==0.5.0.dev20240830+cu121 --index-url https://download.pytorch.org/whl/nightly/cu121
python3
>>> import torch
>>> from torchao.dtypes.nf4tensor import NF4Tensor
>>> torch.empty(0, device=torch.device('cuda:0'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Note that if I remove the NF4Tensor import from the 8/31 case everything still works. Is this related to #790? If so, what's the recommendation? Just force installation of 8/29 PyTorch nightly? (This is relevant for our nightly builds as well)

**Comment by msaroufim** [comment]
AFK today but most likely culprit is this is a problem in core


<img width="1165" alt="Screenshot 2024-09-02 at 1 07 49 PM" src="https://github.com/user-attachments/assets/ba97d54b-731c-49d6-944d-4bd4f1bc216e">

**Comment by drisspg** [comment]
https://github.com/pytorch/pytorch/issues/135126
The offending PR has been reverted on main

**Comment by ebsmothers** [comment]
Just coming back to this now. After the revert I think this should be good to close
