### ISSUE TITLE
quantization subclass typo

### ISSUE THREAD

**Issue by YihengBrianWu** [pytorch/ao#846]
Hi,
I'm testing the inner code of quantization. For this line: 
https://github.com/pytorch/ao/blob/main/torchao/quantization/subclass.py#L234
Is this a typo?
I don't see any refernce of qscales.

**Comment by supriyar** [comment]
@YihengBrianWu indeed this looks like a typo. 

would you be interested in opening a PR with the fix? If not tagging @jainapurva to put up a fix for this

**Comment by YihengBrianWu** [comment]
> @YihengBrianWu indeed this looks like a typo.
> 
> would you be interested in opening a PR with the fix? If not tagging @jainapurva to put up a fix for this

I'm glad to do this!
I open a PR: https://github.com/pytorch/ao/pull/860
