### ISSUE TITLE
torchao.ops import error on aarch64 linux

### ISSUE THREAD

**Issue by ng-05** [pytorch/ao#929]
Hello team,

I am compiling pytorch/ao package from source on aarch64 linux. 
The build and installtion seems to be working perfectly fine unitll I do and import : `import torchao.ops`

The issue is not with not any single op. Its with all the op registration in `ops.py`

To reproduce:
```

- git clone https://github.com/pytorch/ao.git --recursive
- cd ao
- python setup.py install 
- python -c 'import torchao.ops'

```

This import errors out with below error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sudouser/workspace/torch_ao_tests/ao/torchao/ops.py", line 42, in <module>
    def _(EXPONENT, MANTISSA, _in_feats, _weights, _scales, splitK = 1):
  File "/home/sudouser/workspace/torch_ao_tests/ao/torchao/ops.py", line 10, in decorator
    return torch.library.register_fake(f"{name}")(func)
  File "/home/sudouser/workspace/new_tools/tools/dev/pytorch/venv_latest/lib/python3.10/site-packages/torch/library.py", line 795, in register
    use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/home/sudouser/workspace/new_tools/tools/dev/pytorch/venv_latest/lib/python3.10/site-packages/torch/library.py", line 184, in _register_fake
    handle = entry.fake_impl.register(func_to_register, source)
  File "/home/sudouser/workspace/new_tools/tools/dev/pytorch/venv_latest/lib/python3.10/site-packages/torch/_library/fake_impl.py", line 31, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchao::quant_llm_linear does not exist
```

**Comment by digantdesai** [comment]
cc @jerryzh168 - have you seen this before? Or do we have a ci for Aarch64 Linux?

**Comment by msaroufim** [comment]
Generally the answer to do we support hardware architecture X is most likely gonna be no :P 

because AO isn't a pure python package we have to manually support CI for more HW architectures for now we support ARM Mac and Linux and that's about it

We've been very interested in supporting more HW architectures so hopefully we'll share some updates soon

**Comment by jerryzh168** [comment]
> cc @jerryzh168 - have you seen this before? Or do we have a ci for Aarch64 Linux?

we don't right now, and it seems to be blocking torchchat, and I think we'd need to add it: https://github.com/pytorch/ao/issues/922 cc @msaroufim

**Comment by gau-nernst** [comment]
I'm also curious, if torchao can be compiled and works on CPU and Mac M1, it should work with aarch64 Linux too?

I believe the ops itself are defined in the following CPP files

https://github.com/pytorch/ao/blob/main/torchao/csrc/tensor_core_tiled_layout.cpp
https://github.com/pytorch/ao/blob/main/torchao/csrc/fp6_llm.cpp
https://github.com/pytorch/ao/blob/main/torchao/csrc/sparse_marlin.cpp

So for some reasons these CPP files are not compiled when someone runs `python setup.py install`? `setup.py` doesn't seem to include any ARM-specific logic, so perhaps it has to do with the build system?

Semi-related. In `ops.py`, should we check if an op is defined before registering their fake impl, and define it in python if it isn't? Can be useful when torchao is install with `USE_CPP=0` too.

https://github.com/pytorch/ao/blob/2dea31543635ad747e52047f5091fe0b490c3807/torchao/ops.py#L9-L12

**Comment by jerryzh168** [comment]
@gau-nernst yeah I believe it's just because we haven't added aarch64 in github flows, something like this: https://github.com/pytorch/vision/blob/main/.github/workflows/build-wheels-aarch64-linux.yml

> define it in python if it isn't

not sure I follow this one, you mean we register an empty op if it's not defined?

**Comment by gau-nernst** [comment]
@jerryzh168 The error happens when installing torchao from source, so CI / pre-built binaries shouldn't matter

> define it in python if it isn't

I believe 

https://github.com/pytorch/ao/blob/2dea31543635ad747e52047f5091fe0b490c3807/torchao/csrc/fp6_llm.cpp#L5-L8

is equivalent to

https://github.com/pytorch/ao/blob/2dea31543635ad747e52047f5091fe0b490c3807/torchao/kernel/intmm_triton.py#L305-L307

The error happens because the op is not defined (from my understanding). So for example, when register fake impl of `quant_llm_linear`, we can check if it is already defined. If it is not, we can define it in python, like the 2nd code snippet.

**Comment by jerryzh168** [comment]
@gau-nernst makes sense, please open a PR. I was talking about something different

**Comment by gau-nernst** [comment]
@ng-05 I believe your error actually comes from the fact that the C++ compiler does not run when you install torchao from source. Can you also double check this?

**Comment by gau-nernst** [comment]
@ng-05 Can you check if the latest main works for you?

@jerryzh168 I think we can close this (and #913) if @ng-05 verifies that no more errors appear, while #922 can be kept open.

**Comment by ng-05** [comment]
Thanks @gau-nernst and @jerryzh168 . I just tested with latest changes and import works perfectly fine. Thanks for fixing it quickly.
I will close this issue now
