### ISSUE TITLE
int8 mixed precision training flaky tests?

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/ao#945]
see https://github.com/pytorch/ao/actions/runs/11025008549/job/30659811413

**Comment by jerryzh168** [comment]
cc @gau-nernst can you take a look?

**Comment by gau-nernst** [comment]
Yes I sometimes observed it too. Maybe just increase tolerance? (but rn the tolerance is alr quite high...). Will double check and get back to u.

**Comment by jerryzh168** [comment]
should be fixed now, thanks @gau-nernst !
