### ISSUE TITLE
`test_choose_qparams_token_asym` failing in nightly

### ISSUE THREAD

**Issue by gau-nernst** [pytorch/ao#970]
New errors with PyTorch nightly (both CPU and CUDA)

https://github.com/pytorch/ao/actions/runs/11087952684/job/30807207991

cc @jerryzh168

**Comment by jerryzh168** [comment]
there is a recent change in pytorch I think, will fix on Monday

**Comment by msaroufim** [comment]
Pinning here in the meantime https://github.com/pytorch/ao/pull/981
